### PR TITLE
Support draft course

### PR DESCRIPTION
**Pull request by 01ttouch**
https://github.com/r0oth3x49/udemy-dl/issues/391

### CODE REVIEW

**Comment by r0oth3x49** [comment]
did you tested that the course contents are returned?

**Comment by 01ttouch** [comment]
returned? you mean ?

**Comment by 01ttouch** [comment]
i saw 3 types of draft course already: not ready yet, waiting for udemy approval and bought but no longer available to purchase.

**Comment by 01ttouch** [comment]
Tested ofc

draft

**Pull request closed without merging**
