### PR TITLE
Fixed #110

### LINKED ISSUE #110: Udemy Login Error
I have some error with login to udemy.

```
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 725, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/home/mynameismaxz/udemy-dl/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/home/mynameismaxz/udemy-dl/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/home/mynameismaxz/udemy-dl/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/home/mynameismaxz/udemy-dl/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'<!--(?:(?!<!--).)*-->', '', html)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

### PR DESCRIPTION
**Pull request by serhattsnmz**

### CODE REVIEW

**Comment by r0oth3x49** [comment]
@serhattsnmz thanks for your PR but the solution to this is already discussed in #98, #100 so i will not merge this PR.

**Comment by serhattsnmz** [comment]
I looked at them, but I could not see the solituon of that but installing pyOpenSSL. What is the other solutions?

**Comment by r0oth3x49** [comment]
### sudo pip install requests[security] --upgrade

this works for me as well as others.

**Comment by serhattsnmz** [comment]
I tried but It didn't work for me.

**Comment by serhattsnmz** [comment]
That worked. Would you like to add that info to Readme file?

**Comment by r0oth3x49** [comment]
@serhattsnmz i already did in [this](https://github.com/r0oth3x49/udemy-dl/commit/e2ea80a59ac3c1d94157770f0bf4faaa4898ca00) commit you can check.

**Comment by serhattsnmz** [comment]
I saw this, but main issue is writing that without *sudo*. If you don't write it, you will get the same error.

**Comment by r0oth3x49** [comment]
you want to say that this solution is not working without sudo or what?

**Comment by serhattsnmz** [comment]
`sudo pip install requests[security] --upgrade`
this code is not working without **sudo**. 
That means this code below is also not working without **sudo** for avoiding this issue.
`pip install -r requirements.txt --upgrade`

**Pull request closed without merging**
