### PR TITLE
Change versions macOS

### PR DESCRIPTION
**Pull request by Nocxy**
Hi

It works on later macOS version than announced. I just tried it.

Thanks in advance.

### CODE REVIEW

**Comment by r0oth3x49** [comment]
@Nocxy thanks for checking i really appreciate. but purpose of [tested on](https://github.com/r0oth3x49/udemy-dl#tested-on) heading is to show that it works on all platform instead of version of of platform. that's why i cannot merge your PR. Again thank you so much  for testing.

**Comment by Nocxy** [comment]
Hi r0oth3x49

The purpose of Github is collaborative work. One cannot say "hey, I tested on every platform out there".

You didn't merge any suggestion posted by someone who wasn't you. However, the reason you gave me was probably the worst I could imagine. Everyone can see bad faith here. You wrote "Mac OSX 10.9.5 (tested with super user)" and then said "[...] purpose of tested on heading is to show that it works on all platform instead of specific platform version"... You didn't wrote "Mac OSX up to 10.9.5 (tested with super user)".

Indeed, in the history, every change was yours inspite of good suggestions made in the pull requests.

For months, there was a problem: when you asked for a quality not available, you had to confirm on every lesson that you wanted to download the best quality ("max_url"). I doubt I was the only one making changes in his own files to implement a way to se the variable user_choice definitely equals to the best quality available.

So let me ask you a question: why did you publish it instead of keeping it for yourself?

Yours cordially,
Nocxy

**Comment by Nocxy** [comment]
Hi r0oth3x49

No prob, I'm not in a dev project right now so I have more time.

I may have taken this point wrong, I agree. I'm just trying to say that it could have been buggy on more recent macOS versions. I didn't try on Fedora but Linux distro are so different that I'm not sure everything would work.

The "problem" here is that people are trying to make suggestions to help you (honestly, which other reason would it be? Neither them nor you are paid to help GitHub repos) and you refuse them all.

On Bitbucket, you could get a private repo (for free, I must precise, but you seem to already pay 7$ monthly for private repos...) if you do not want anyone to post something. I know that you cannot disable pull requests but there is a "fix" (well... a workaround) [here](https://github.com/isaacs/github/issues/1191) if you want to avoid pull requests.

Everybody hates Udemy's video system since it's programmed with donkey's ass. We're just here to help this project. Well... I'd say that atm there's nothing to add since HTML pages can be downloaded but who knows?

Accept help from people, dude :)

Good luck :)

**Comment by r0oth3x49** [comment]
@Nocxy okay here is my bad, the way i listed platforms was to avoid other to ask me if this works on that platform or not & they can test by their own instead asking me & if it does not work then they can report an issue facing on which platform version it occurs.

I really appreciate each & every person out there on Github who use to give a PR or suggest some thing great to add on & i 'm also aware of that each user using this Repo can see all of the PR/Issues & whats going on in the comments of PR. 


My point is here if a user Request a PR if he/she can make sure that the PR he/she is doing is not specific to python version / OS platform & is a valid bug fix i will definitely merge that PR Soon i will add a file called **Contributing**  in which i will add a template for PR if the PR does not follow that template i will close.

You can check all of the PRs currently done to this repository and what was my reply to them.

**Comment by Nocxy** [comment]
Hi,

If you really wrote this part only to say that it works on various OS, why did you add Ubuntu? You already mentioned that it was working with Kali.

**Pull request closed without merging**
